### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by nazikus** [nazar-ivantsiv/peppers-ghost#4]
Для початку реструктуруй код таким чином, щоб GUI, ініціалізація відео, геометрична обробка і сегментація були повністю розділені (в різних файлах/класах). Тобто щоб я міг легко замінити наприклад гуі і не чіпати решту коду, або замінити 4 трикутні маски на 5 пентагонів і не чіпати при цьому гуі і сегментацію, або замінити відео інпут з веб камери на відеострім і з інету - так щоб я замінив один клас інпуту а все решту залишилось не змінним.

**Comment by nazar-ivantsiv** [comment]
Ясно, зроблю.
Буду мати напружений початок тижня... орієнтовно на **четвер-п’ятницю** буде готово.
Буду тримати в курсі.

**Comment by nazar-ivantsiv** [comment]
Спробував розділити на модулі. _(branch 'ref')_
- Якщо я пішо не тим шляхом, то накидай плз схематично, як би ти бачив послідовність дій в методі Ghost.run(). І я буду від цього відштовхуватись.
- Якщо - може бути, то чекаю на зауваження.

P.S.: Новими трекбарами 'angle' і 'projections' можна створити зображення більше, ніж з 4ма проекціями (деф. до 10)
