### ISSUE TITLE
Videofile playback is broken

### ISSUE THREAD

**Issue by nazikus** [nazar-ivantsiv/peppers-ghost#7]

**Comment by nazar-ivantsiv** [comment]
Issue fixed check the last commit ([487d5e0129b7c14489f3a63be16130d128b499e3](https://github.com/nazar-ivantsiv/peppers-ghost/commit/487d5e0129b7c14489f3a63be16130d128b499e3)).

**Comment by nazikus** [comment]
ого, реактивно :)

пс. ти можеш вказувати в коміті номер issue словом fix або close, і він автоматично після пушу закриє issue з коментом який вкаже на номер коміту. Напр., git commit -m "video playback, close #10"
https://help.github.com/articles/closing-issues-via-commit-messages/
